<?php /* Smarty version Smarty-3.1.7, created on 2018-08-14 20:17:53
         compiled from "/var/www/html/BMLGDEMO65/includes/runtime/../../layouts/vlayout/modules/ProcessFlow/LineItemsEdit.tpl" */ ?>
<?php /*%%SmartyHeaderCode:13934657815b7338f1df9a80-25595906%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    '13512ca1f3a1e1215e323292a98356e161031d6a' => 
    array (
      0 => '/var/www/html/BMLGDEMO65/includes/runtime/../../layouts/vlayout/modules/ProcessFlow/LineItemsEdit.tpl',
      1 => 1532585234,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '13934657815b7338f1df9a80-25595906',
  'function' => 
  array (
  ),
  'variables' => 
  array (
    'USER_MODEL' => 0,
    'MODULE' => 0,
    'CURRENT_USER_MODEL' => 0,
    'row_no' => 0,
    'GRID1' => 0,
    'GRID2' => 0,
    'GRID3' => 0,
    'GRID4' => 0,
  ),
  'has_nocache_code' => false,
  'version' => 'Smarty-3.1.7',
  'unifunc' => 'content_5b7338f20e00b',
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_5b7338f20e00b')) {function content_5b7338f20e00b($_smarty_tpl) {?>

<input type="hidden" class="numberOfCurrencyDecimal" value="<?php echo $_smarty_tpl->tpl_vars['USER_MODEL']->value->get('no_of_currency_decimals');?>
" /><?php $_smarty_tpl->tpl_vars['ALL_ACTIVEUSER_LIST'] = new Smarty_variable($_smarty_tpl->tpl_vars['USER_MODEL']->value->getAccessibleUsers(), null, 0);?><table class="table table-bordered blockContainer grid1" id="grid1"><thead><tr><th colspan="7"><span class="inventoryLineItemHeader"><?php echo vtranslate('Materials',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</span></th></tr><tr><td><b><?php echo vtranslate('Tools',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td><td><b><?php echo vtranslate('Product Category',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td><td><b><?php echo vtranslate('Product Name',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td><!--td><b><?php echo vtranslate('Batch Name',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td--><td  width="100px"><b><?php echo vtranslate('Present Stock',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td><td width="100px"><b><?php echo vtranslate('Issued Qty',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td><td><b><?php echo vtranslate('Issued By',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td><td><b><?php echo vtranslate('Remarks',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td></tr></thead><tbody id="idtbodyGrid1"><tr id="row0" class="hide grid1CloneCopy"><?php $_smarty_tpl->tpl_vars['row_no'] = new Smarty_variable(0, null, 0);?><?php $_smarty_tpl->tpl_vars["userid"] = new Smarty_variable($_smarty_tpl->tpl_vars['CURRENT_USER_MODEL']->value->get('id'), null, 0);?><?php $_smarty_tpl->tpl_vars["productid"] = new Smarty_variable(("grid1productid").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["productName"] = new Smarty_variable(("grid1productName").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["productcategory"] = new Smarty_variable(("grid1productcategory").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["batchid"] = new Smarty_variable(("grid1batchid").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["issuedqty"] = new Smarty_variable(("grid1issuedqty").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["prasentqty"] = new Smarty_variable(("grid1prasentqty").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["issuedby"] = new Smarty_variable(("grid1issuedby").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["remarks"] = new Smarty_variable(("grid1remarks").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php echo $_smarty_tpl->getSubTemplate (vtemplate_path("LineItemsContent.tpl",'ProcessFlow'), $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, null, null, array(), 0);?>
</tr><?php  $_smarty_tpl->tpl_vars['data'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['data']->_loop = false;
 $_smarty_tpl->tpl_vars['row_no'] = new Smarty_Variable;
 $_from = $_smarty_tpl->tpl_vars['GRID1']->value; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['data']->key => $_smarty_tpl->tpl_vars['data']->value){
$_smarty_tpl->tpl_vars['data']->_loop = true;
 $_smarty_tpl->tpl_vars['row_no']->value = $_smarty_tpl->tpl_vars['data']->key;
?><?php $_smarty_tpl->tpl_vars['row_no'] = new Smarty_variable($_smarty_tpl->tpl_vars['row_no']->value+1, null, 0);?><?php $_smarty_tpl->tpl_vars["productid"] = new Smarty_variable(("grid1productid").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["productName"] = new Smarty_variable(("grid1productName").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["productcategory"] = new Smarty_variable(("grid1productcategory").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["batchid"] = new Smarty_variable(("grid1batchid").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["issuedqty"] = new Smarty_variable(("grid1issuedqty").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["prasentqty"] = new Smarty_variable(("grid1prasentqty").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["issuedby"] = new Smarty_variable(("grid1issuedby").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["remarks"] = new Smarty_variable(("grid1remarks").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><tr id="row<?php echo $_smarty_tpl->tpl_vars['row_no']->value;?>
" class="grid1ItemRow"><?php echo $_smarty_tpl->getSubTemplate (vtemplate_path("LineItemsContent.tpl",'ProcessFlow'), $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, null, null, array(), 0);?>
</tr><?php } ?><?php if (count($_smarty_tpl->tpl_vars['GRID1']->value)==0){?><?php $_smarty_tpl->tpl_vars['row_no'] = new Smarty_variable(1, null, 0);?><?php $_smarty_tpl->tpl_vars["productid"] = new Smarty_variable(("grid1productid").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["productName"] = new Smarty_variable(("grid1productName").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["productcategory"] = new Smarty_variable(("grid1productcategory").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["batchid"] = new Smarty_variable(("grid1batchid").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["issuedqty"] = new Smarty_variable(("grid1issuedqty").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["prasentqty"] = new Smarty_variable(("grid1prasentqty").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["issuedby"] = new Smarty_variable(("grid1issuedby").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["remarks"] = new Smarty_variable(("grid1remarks").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><tr id="row1" class="grid1ItemRow"><?php echo $_smarty_tpl->getSubTemplate (vtemplate_path("LineItemsContent.tpl",'ProcessFlow'), $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, null, null, array(), 0);?>
</tr><?php }?></tbody></table><div class="row-fluid verticalBottomSpacing"><div><div class="btn-group"><button type="button" class="btn addButton" id="addGrid1"><i class="icon-plus"></i><strong> <?php echo vtranslate('Add Materials',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</strong></button></div></div></div><!-- Vessels Grid2 Started here --><table class="table table-bordered blockContainer grid2" id="grid2"><thead><tr><th colspan="7"><span class="inventoryLineItemHeader"><?php echo vtranslate('Vessels',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</span></th></tr><tr><td><b><?php echo vtranslate('Tools',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td><td><b><?php echo vtranslate('Assets Category',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td><td><b><?php echo vtranslate('Assets Name',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td><!--td><b><?php echo vtranslate('Batch Name',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td--><!--<td  width="100px"><b><?php echo vtranslate('Present Stock',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td>--><td width="100px"><b><?php echo vtranslate('Issued Qty',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td><td><b><?php echo vtranslate('Issued By',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td><td><b><?php echo vtranslate('Remarks',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td></tr></thead><tbody id="idtbodyGrid2"><tr id="row0" class="hide grid2CloneCopy"><?php $_smarty_tpl->tpl_vars['row_no'] = new Smarty_variable(0, null, 0);?><?php $_smarty_tpl->tpl_vars["assetsid"] = new Smarty_variable(("grid2assetsid").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["assetName"] = new Smarty_variable(("grid2assetName").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["assetcategory"] = new Smarty_variable(("grid2assetcategory").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["issuedqty"] = new Smarty_variable(("grid2issuedqty").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["issuedby"] = new Smarty_variable(("grid2issuedby").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["remarks"] = new Smarty_variable(("grid2remarks").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php echo $_smarty_tpl->getSubTemplate (vtemplate_path("LineItemsContentAsset.tpl",'ProcessFlow'), $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, null, null, array(), 0);?>
</tr><?php  $_smarty_tpl->tpl_vars['data'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['data']->_loop = false;
 $_smarty_tpl->tpl_vars['row_no'] = new Smarty_Variable;
 $_from = $_smarty_tpl->tpl_vars['GRID2']->value; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['data']->key => $_smarty_tpl->tpl_vars['data']->value){
$_smarty_tpl->tpl_vars['data']->_loop = true;
 $_smarty_tpl->tpl_vars['row_no']->value = $_smarty_tpl->tpl_vars['data']->key;
?><?php $_smarty_tpl->tpl_vars['row_no'] = new Smarty_variable($_smarty_tpl->tpl_vars['row_no']->value+1, null, 0);?><?php $_smarty_tpl->tpl_vars["assetsid"] = new Smarty_variable(("grid2assetsid").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["assetName"] = new Smarty_variable(("grid2assetName").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["assetcategory"] = new Smarty_variable(("grid2assetcategory").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["issuedqty"] = new Smarty_variable(("grid2issuedqty").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["issuedby"] = new Smarty_variable(("grid2issuedby").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["remarks"] = new Smarty_variable(("grid2remarks").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><tr id="row<?php echo $_smarty_tpl->tpl_vars['row_no']->value;?>
" class="grid2ItemRow" ><?php echo $_smarty_tpl->getSubTemplate (vtemplate_path("LineItemsContentAsset.tpl",'ProcessFlow'), $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, null, null, array(), 0);?>
</tr><?php } ?><?php if (count($_smarty_tpl->tpl_vars['GRID2']->value)==0){?><?php $_smarty_tpl->tpl_vars['row_no'] = new Smarty_variable(1, null, 0);?><?php $_smarty_tpl->tpl_vars["assetsid"] = new Smarty_variable(("grid2assetsid").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["assetName"] = new Smarty_variable(("grid2assetName").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["assetcategory"] = new Smarty_variable(("grid2assetcategory").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["issuedqty"] = new Smarty_variable(("grid2issuedqty").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["issuedby"] = new Smarty_variable(("grid2issuedby").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["remarks"] = new Smarty_variable(("grid2remarks").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><tr id="row1" class="grid2ItemRow"><?php echo $_smarty_tpl->getSubTemplate (vtemplate_path("LineItemsContentAsset.tpl",'ProcessFlow'), $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, null, null, array(), 0);?>
</tr><?php }?></tbody></table><div class="row-fluid verticalBottomSpacing"><div><div class="btn-group"><button type="button" class="btn addButton" id="addGrid2"><i class="icon-plus"></i><strong> <?php echo vtranslate('Add Vessels',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</strong></button></div></div></div><!-- Ended here --><!-- Tools Grid 3 --><table class="table table-bordered blockContainer grid3" id="grid3"><thead><tr><th colspan="7"><span class="inventoryLineItemHeader"><?php echo vtranslate('Tools',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</span></th></tr><tr><td><b><?php echo vtranslate('Tools',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td><td><b><?php echo vtranslate('Asset Category',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td><td><b><?php echo vtranslate('Asset Name',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td><!--td><b><?php echo vtranslate('Batch Name',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td--><!--<td  width="100px"><b><?php echo vtranslate('Present Stock',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td>--><td width="100px"><b><?php echo vtranslate('Issued Qty',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td><td><b><?php echo vtranslate('Issued By',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td><td><b><?php echo vtranslate('Remarks',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td></tr></thead><tbody id="idtbodyGrid3"><tr id="row0" class="hide grid3CloneCopy"><?php $_smarty_tpl->tpl_vars['row_no'] = new Smarty_variable(0, null, 0);?><?php $_smarty_tpl->tpl_vars["assetsid"] = new Smarty_variable(("grid3assetsid").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["assetName"] = new Smarty_variable(("grid3assetName").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["assetcategory"] = new Smarty_variable(("grid3assetcategory").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["issuedqty"] = new Smarty_variable(("grid3issuedqty").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["issuedby"] = new Smarty_variable(("grid3issuedby").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["remarks"] = new Smarty_variable(("grid3remarks").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php echo $_smarty_tpl->getSubTemplate (vtemplate_path("LineItemsContentAsset.tpl",'ProcessFlow'), $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, null, null, array(), 0);?>
</tr><?php  $_smarty_tpl->tpl_vars['data'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['data']->_loop = false;
 $_smarty_tpl->tpl_vars['row_no'] = new Smarty_Variable;
 $_from = $_smarty_tpl->tpl_vars['GRID3']->value; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['data']->key => $_smarty_tpl->tpl_vars['data']->value){
$_smarty_tpl->tpl_vars['data']->_loop = true;
 $_smarty_tpl->tpl_vars['row_no']->value = $_smarty_tpl->tpl_vars['data']->key;
?><?php $_smarty_tpl->tpl_vars['row_no'] = new Smarty_variable($_smarty_tpl->tpl_vars['row_no']->value+1, null, 0);?><?php $_smarty_tpl->tpl_vars["assetsid"] = new Smarty_variable(("grid3assetsid").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["assetName"] = new Smarty_variable(("grid3assetName").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["assetcategory"] = new Smarty_variable(("grid3assetcategory").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["issuedqty"] = new Smarty_variable(("grid3issuedqty").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["issuedby"] = new Smarty_variable(("grid3issuedby").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["remarks"] = new Smarty_variable(("grid3remarks").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><tr id="row<?php echo $_smarty_tpl->tpl_vars['row_no']->value;?>
" class="grid3ItemRow" ><?php echo $_smarty_tpl->getSubTemplate (vtemplate_path("LineItemsContentAsset.tpl",'ProcessFlow'), $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, null, null, array(), 0);?>
</tr><?php } ?><?php if (count($_smarty_tpl->tpl_vars['GRID3']->value)==0){?><?php $_smarty_tpl->tpl_vars['row_no'] = new Smarty_variable(1, null, 0);?><?php $_smarty_tpl->tpl_vars["assetsid"] = new Smarty_variable(("grid3assetsid").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["assetName"] = new Smarty_variable(("grid3assetName").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["assetcategory"] = new Smarty_variable(("grid3assetcategory").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["issuedqty"] = new Smarty_variable(("grid3issuedqty").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["issuedby"] = new Smarty_variable(("grid3issuedby").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["remarks"] = new Smarty_variable(("grid3remarks").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><tr id="row1" class="grid3ItemRow"><?php echo $_smarty_tpl->getSubTemplate (vtemplate_path("LineItemsContentAsset.tpl",'ProcessFlow'), $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, null, null, array(), 0);?>
</tr><?php }?></tbody></table><div class="row-fluid verticalBottomSpacing"><div><div class="btn-group"><button type="button" class="btn addButton" id="addGrid3"><i class="icon-plus"></i><strong> <?php echo vtranslate('Add Tools',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</strong></button></div></div></div><!-- Grid3 ended here --><!-- Grid 4 Machinery Started here --><table class="table table-bordered blockContainer grid4" id="grid4"><thead><tr><th colspan="7"><span class="inventoryLineItemHeader"><?php echo vtranslate('Machinery',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</span></th></tr><tr><td><b><?php echo vtranslate('Tools',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td><td><b><?php echo vtranslate('Asset Category',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td><td><b><?php echo vtranslate('Asset Name',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td><!--td><b><?php echo vtranslate('Batch Name',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td--><!--<td  width="100px"><b><?php echo vtranslate('Present Stock',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td>--><td width="100px"><b><?php echo vtranslate('Issued Qty',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td><td><b><?php echo vtranslate('Issued By',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td><td><b><?php echo vtranslate('Remarks',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</b></td></tr></thead><tbody id="idtbodyGrid4"><tr id="row0" class="hide grid4CloneCopy"><?php $_smarty_tpl->tpl_vars['row_no'] = new Smarty_variable(0, null, 0);?><?php $_smarty_tpl->tpl_vars["assetsid"] = new Smarty_variable(("grid4assetsid").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["assetName"] = new Smarty_variable(("grid4assetName").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["assetcategory"] = new Smarty_variable(("grid4assetcategory").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["issuedqty"] = new Smarty_variable(("grid4issuedqty").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["issuedby"] = new Smarty_variable(("grid4issuedby").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["remarks"] = new Smarty_variable(("grid4remarks").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php echo $_smarty_tpl->getSubTemplate (vtemplate_path("LineItemsContentAsset.tpl",'ProcessFlow'), $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, null, null, array(), 0);?>
</tr><?php  $_smarty_tpl->tpl_vars['data'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['data']->_loop = false;
 $_smarty_tpl->tpl_vars['row_no'] = new Smarty_Variable;
 $_from = $_smarty_tpl->tpl_vars['GRID4']->value; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['data']->key => $_smarty_tpl->tpl_vars['data']->value){
$_smarty_tpl->tpl_vars['data']->_loop = true;
 $_smarty_tpl->tpl_vars['row_no']->value = $_smarty_tpl->tpl_vars['data']->key;
?><?php $_smarty_tpl->tpl_vars['row_no'] = new Smarty_variable($_smarty_tpl->tpl_vars['row_no']->value+1, null, 0);?><?php $_smarty_tpl->tpl_vars["assetsid"] = new Smarty_variable(("grid4assetsid").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["assetName"] = new Smarty_variable(("grid4assetName").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["assetcategory"] = new Smarty_variable(("grid4assetcategory").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["issuedqty"] = new Smarty_variable(("grid4issuedqty").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["issuedby"] = new Smarty_variable(("grid4issuedby").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["remarks"] = new Smarty_variable(("grid4remarks").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><tr id="row<?php echo $_smarty_tpl->tpl_vars['row_no']->value;?>
" class="grid4ItemRow"><?php echo $_smarty_tpl->getSubTemplate (vtemplate_path("LineItemsContentAsset.tpl",'ProcessFlow'), $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, null, null, array(), 0);?>
</tr><?php } ?><?php if (count($_smarty_tpl->tpl_vars['GRID4']->value)==0){?><?php $_smarty_tpl->tpl_vars['row_no'] = new Smarty_variable(1, null, 0);?><?php $_smarty_tpl->tpl_vars["assetsid"] = new Smarty_variable(("grid4assetsid").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["assetName"] = new Smarty_variable(("grid4assetName").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["assetcategory"] = new Smarty_variable(("grid4assetcategory").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["issuedqty"] = new Smarty_variable(("grid4issuedqty").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["issuedby"] = new Smarty_variable(("grid4issuedby").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["remarks"] = new Smarty_variable(("grid4remarks").($_smarty_tpl->tpl_vars['row_no']->value), null, 0);?><tr id="row1" class="grid4ItemRow"><?php echo $_smarty_tpl->getSubTemplate (vtemplate_path("LineItemsContentAsset.tpl",'ProcessFlow'), $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, null, null, array(), 0);?>
</tr><?php }?></tbody></table><div class="row-fluid verticalBottomSpacing"><div><div class="btn-group"><button type="button" class="btn addButton" id="addGrid4"><i class="icon-plus"></i><strong> <?php echo vtranslate('Add Machinery',$_smarty_tpl->tpl_vars['MODULE']->value);?>
</strong></button></div></div></div><!-- Grid 4 Machinery Ended here --><?php }} ?>